name: Deploy via SFTP (rsync)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SRC_DIR: ./
      EXCLUDES: |
        --exclude ".git/" \
        --exclude ".github/" \
        --exclude "**/.DS_Store" \
        --exclude "**/node_modules/" \
        --exclude "**/*.log"
      SSH_OPTS: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show runner disk space
        run: df -h

      - name: Install rsync and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client sshpass

      - name: Validate required secrets
        run: |
          require() { [ -z "$1" ] && { echo "Missing secret: $2"; exit 1; } || true; }
          require "${{ secrets.SFTP_HOST }}" SFTP_HOST
          require "${{ secrets.SFTP_USERNAME }}" SFTP_USERNAME
          require "${{ secrets.SFTP_REMOTE_PATH }}" SFTP_REMOTE_PATH
          # One of SFTP_SSH_KEY or SFTP_PASSWORD must be present
          if [ -z "${{ secrets.SFTP_SSH_KEY }}" ] && [ -z "${{ secrets.SFTP_PASSWORD }}" ]; then
            echo "Provide either SFTP_SSH_KEY or SFTP_PASSWORD as a repository secret." && exit 1
          fi

      - name: Write SSH key (if provided)
        if: secrets.SFTP_SSH_KEY != ''
        run: |
          echo "Writing SSH key"
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Deploy with SSH key (rsync over SSH)
        if: secrets.SFTP_SSH_KEY != ''
        run: |
          RSYNC_RSH="ssh -i ~/.ssh/deploy_key $SSH_OPTS -p ${PORT:-22}"
          rsync -az --delete $EXCLUDES -e "$RSYNC_RSH" "$SRC_DIR" "${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_REMOTE_PATH }}"
        env:
          PORT: ${{ secrets.SFTP_PORT }}

      - name: Deploy with password (sshpass + rsync over SSH)
        if: secrets.SFTP_SSH_KEY == ''
        run: |
          echo "Using password auth via sshpass"
          sshpass -p "${{ secrets.SFTP_PASSWORD }}" \
            rsync -az --delete $EXCLUDES -e "ssh $SSH_OPTS -p ${PORT:-22}" "$SRC_DIR" \
            "${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_REMOTE_PATH }}"
        env:
          PORT: ${{ secrets.SFTP_PORT }}
